### ISSUE TITLE
Using arrow keys didn't seem to work

### ISSUE THREAD

**Issue by domjanabi** [karochrapla/pomodoro_timer#11]
i pressed them but nothing happened

**Comment by BigK-hub** [comment]
did you make sure to press either p or b beforehand?

**Comment by domjanabi** [comment]
alright this time i made sure to press them beforehand
a few problems:
i managed to make the program crash by going to the left when setting the hours
when i press the up/down key it sometimes adds/subtracts two instead of one to/from the value

**Comment by BigK-hub** [comment]
fixed the out of bounds issue
