### ISSUE TITLE
Consider using the OLC Console Game Engine

### ISSUE THREAD

**Issue by domjanabi** [karochrapla/pomodoro_timer#9]
It's more useful for things that are predominantly text-based.

**Comment by BigK-hub** [comment]
would I still be able to have the whole GUI situation with the console game engine?

**Comment by domjanabi** [comment]
Yes, although the mouse seems to be accessible in form of member variables, instead of methods.

**Comment by BigK-hub** [comment]
I think porting it to console game engine would be a bit too much of a hastle atm. for now i will stay with the pge
